//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpress.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelExpress.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio debe ser mayor al día de hoy.
        /// </summary>
        public static string BeginDateShouldBeGraterThanToday {
            get {
                return ResourceManager.GetString("BeginDateShouldBeGraterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar la orden de pago..
        /// </summary>
        public static string CreateOrderAddBillingError {
            get {
                return ResourceManager.GetString("CreateOrderAddBillingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los detalles de la orden en base de datos..
        /// </summary>
        public static string CreateOrderDetailsError {
            get {
                return ResourceManager.GetString("CreateOrderDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar la orden en base de datos..
        /// </summary>
        public static string CreateOrderHeaderError {
            get {
                return ResourceManager.GetString("CreateOrderHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente.
        /// </summary>
        public static string CustomersAddPageTitle {
            get {
                return ResourceManager.GetString("CustomersAddPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de cliente.
        /// </summary>
        public static string CustomersDetailsPageTitle {
            get {
                return ResourceManager.GetString("CustomersDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda por nombre, email, teléfono de casa o celular..
        /// </summary>
        public static string CustomerSearchPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("CustomerSearchPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda de clientes.
        /// </summary>
        public static string CustomerSearchPageTitle {
            get {
                return ResourceManager.GetString("CustomerSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición datos cliente.
        /// </summary>
        public static string CustomersEditPageTitle {
            get {
                return ResourceManager.GetString("CustomersEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una categoria con el mismo nombre..
        /// </summary>
        public static string DuplicateCategoryError {
            get {
                return ResourceManager.GetString("DuplicateCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una excursion en las fechas establecidas..
        /// </summary>
        public static string DuplicateExcursionError {
            get {
                return ResourceManager.GetString("DuplicateExcursionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio debe ser menor a la fecha fin..
        /// </summary>
        public static string EndDateShouldBeGreterThanBeginDateError {
            get {
                return ResourceManager.GetString("EndDateShouldBeGreterThanBeginDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de error: {0}.
        /// </summary>
        public static string GeneratedErrorIdMessage {
            get {
                return ResourceManager.GetString("GeneratedErrorIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando.
        /// </summary>
        public static string Grid_DisplayingLabel {
            get {
                return ResourceManager.GetString("Grid_DisplayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 registros.
        /// </summary>
        public static string Grid_FiftyRows {
            get {
                return ResourceManager.GetString("Grid_FiftyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Página.
        /// </summary>
        public static string Grid_FirstPageLabel {
            get {
                return ResourceManager.GetString("Grid_FirstPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Grid_NextPageLabel {
            get {
                return ResourceManager.GetString("Grid_NextPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Grid_PageLabel {
            get {
                return ResourceManager.GetString("Grid_PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Grid_PageNumberOfLabel {
            get {
                return ResourceManager.GetString("Grid_PageNumberOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Grid_PreviousPageLabel {
            get {
                return ResourceManager.GetString("Grid_PreviousPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registros..
        /// </summary>
        public static string Grid_RowsLabel {
            get {
                return ResourceManager.GetString("Grid_RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Grid_SearchButtonLabel {
            get {
                return ResourceManager.GetString("Grid_SearchButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 registros.
        /// </summary>
        public static string Grid_TenRows {
            get {
                return ResourceManager.GetString("Grid_TenRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 registros.
        /// </summary>
        public static string Grid_ThirtyRows {
            get {
                return ResourceManager.GetString("Grid_ThirtyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 registros.
        /// </summary>
        public static string Grid_TwentyRows {
            get {
                return ResourceManager.GetString("Grid_TwentyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encuentra en la página.
        /// </summary>
        public static string Grid_YouAreOnPageLabel {
            get {
                return ResourceManager.GetString("Grid_YouAreOnPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros incorrectos..
        /// </summary>
        public static string IncorrectParameters {
            get {
                return ResourceManager.GetString("IncorrectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio una excepción al ejecutar el flujo de la aplicación..
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación es invalida..
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un cliente con el mismo correo en el sistema..
        /// </summary>
        public static string NewCustomerComponent_ErrorDuplicateEmail {
            get {
                return ResourceManager.GetString("NewCustomerComponent_ErrorDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar el cliente en BD..
        /// </summary>
        public static string NewCustomerComponent_ErrorSavingCustomerInStorage {
            get {
                return ResourceManager.GetString("NewCustomerComponent_ErrorSavingCustomerInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La order ya genero ordén de pago y no se puede cancelar..
        /// </summary>
        public static string OrderHasPaymentsError {
            get {
                return ResourceManager.GetString("OrderHasPaymentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un producto con la misma descripción..
        /// </summary>
        public static string ProductComponent_DuplicateProduct {
            get {
                return ResourceManager.GetString("ProductComponent_DuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción del producto es requerida..
        /// </summary>
        public static string ProductComponent_ErrorInvalidDescription {
            get {
                return ResourceManager.GetString("ProductComponent_ErrorInvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar el registro en la base de datos..
        /// </summary>
        public static string ProductComponent_ErrorSaveNewProduct {
            get {
                return ResourceManager.GetString("ProductComponent_ErrorSaveNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Producto.
        /// </summary>
        public static string ProductsGridDescription {
            get {
                return ResourceManager.GetString("ProductsGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Productos..
        /// </summary>
        public static string ProductsSearchPageTitle {
            get {
                return ResourceManager.GetString("ProductsSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es requerido..
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
    }
}
