//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpress.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelExpress.Entities.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string AddUpdatePriceCategoryRequest_Description {
            get {
                return ResourceManager.GetString("AddUpdatePriceCategoryRequest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción de la categoría de precios es requerida..
        /// </summary>
        public static string AddUpdatePriceCategoryRequest_Required {
            get {
                return ResourceManager.GetString("AddUpdatePriceCategoryRequest_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud de la descripción de categoría de precios debe ser entre 1 y 100..
        /// </summary>
        public static string AddUpdatePriceCategoryRequest_StringLength_Error {
            get {
                return ResourceManager.GetString("AddUpdatePriceCategoryRequest_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string AppSaveButton {
            get {
                return ResourceManager.GetString("AppSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio.
        /// </summary>
        public static string BeginDate_Display {
            get {
                return ResourceManager.GetString("BeginDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio es requerida.
        /// </summary>
        public static string BeginDate_Required {
            get {
                return ResourceManager.GetString("BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumpleaños.
        /// </summary>
        public static string BirthDate_Display {
            get {
                return ResourceManager.GetString("BirthDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de nacimiento es requerida..
        /// </summary>
        public static string BirthDate_Required {
            get {
                return ResourceManager.GetString("BirthDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Cellphone_Display {
            get {
                return ResourceManager.GetString("Cellphone_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El celular es requerido..
        /// </summary>
        public static string Cellphone_Required {
            get {
                return ResourceManager.GetString("Cellphone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del celular debe ser de 1 a 30 caracteres..
        /// </summary>
        public static string Cellphone_StringLength_Error {
            get {
                return ResourceManager.GetString("Cellphone_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Email_Display {
            get {
                return ResourceManager.GetString("Email_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo es incorrecto..
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico es requerido..
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del correo electrónico debe ser de 1 a 254 caracteres..
        /// </summary>
        public static string Email_StringLength_Error {
            get {
                return ResourceManager.GetString("Email_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin.
        /// </summary>
        public static string EndDate_Display {
            get {
                return ResourceManager.GetString("EndDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha fin es requerida.
        /// </summary>
        public static string EndDate_Required {
            get {
                return ResourceManager.GetString("EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paterno.
        /// </summary>
        public static string FamilyName1_Display {
            get {
                return ResourceManager.GetString("FamilyName1_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido paterno es requerido..
        /// </summary>
        public static string FamilyName1_Required {
            get {
                return ResourceManager.GetString("FamilyName1_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del apellido paterno debe ser de 1 a 50 caracteres..
        /// </summary>
        public static string FamilyName1_StringLength_Error {
            get {
                return ResourceManager.GetString("FamilyName1_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materno.
        /// </summary>
        public static string FamilyName2_Display {
            get {
                return ResourceManager.GetString("FamilyName2_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido materno es requerido..
        /// </summary>
        public static string FamilyName2_Required {
            get {
                return ResourceManager.GetString("FamilyName2_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del apellido materno debe ser de 1 a 50 caracteres..
        /// </summary>
        public static string FamilyName2_StringLength_Error {
            get {
                return ResourceManager.GetString("FamilyName2_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar Envio de correos.
        /// </summary>
        public static string MailEnabled_Display {
            get {
                return ResourceManager.GetString("MailEnabled_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name_Display {
            get {
                return ResourceManager.GetString("Name_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido..
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre debe ser de 1 a 50 caracteres..
        /// </summary>
        public static string Name_StringLength_Error {
            get {
                return ResourceManager.GetString("Name_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del campo observación debe ser entre 1 y 254 carácteres.
        /// </summary>
        public static string ObservationTextStringLenghtValidation {
            get {
                return ResourceManager.GetString("ObservationTextStringLenghtValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar Llamadas.
        /// </summary>
        public static string PhoneCallsEnabled_Display {
            get {
                return ResourceManager.GetString("PhoneCallsEnabled_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud debe ser entre 1 y 254 caracteres..
        /// </summary>
        public static string PhoneCallTextStringLenghtValidation {
            get {
                return ResourceManager.GetString("PhoneCallTextStringLenghtValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción es requerida..
        /// </summary>
        public static string ProductDescription_Required {
            get {
                return ResourceManager.GetString("ProductDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud de la descripción debe ser entre 1 a 100 caracteres. .
        /// </summary>
        public static string ProductDescription_StringLength_Error {
            get {
                return ResourceManager.GetString("ProductDescription_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es requerido..
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Telephone_Display {
            get {
                return ResourceManager.GetString("Telephone_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono es requerido..
        /// </summary>
        public static string Telephone_Required {
            get {
                return ResourceManager.GetString("Telephone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del teléfono debe ser de 1 a 30 caracteres..
        /// </summary>
        public static string Telephone_StringLength_Error {
            get {
                return ResourceManager.GetString("Telephone_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente.
        /// </summary>
        public static string TitleNewCustomerPage {
            get {
                return ResourceManager.GetString("TitleNewCustomerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio unitario.
        /// </summary>
        public static string UnitPrice_Display {
            get {
                return ResourceManager.GetString("UnitPrice_Display", resourceCulture);
            }
        }
    }
}
